version: '2'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5342:5432"
    networks:
     - cubarnetes-network

networks:
  cubarnetes-network: